### ISSUE TITLE
[Bug] Catboost is required, but fails to build (macOS 13.5)

### ISSUE THREAD

**Issue by JulianKlug** [vanderschaarlab/temporai#93]
**Describe the bug**
Building the temporai package from pip or from github fails as catboost is required. 
This is probably linked to #72 were the catboost dependency should have been removed and to https://github.com/catboost/catboost/issues/2371#issue-1692320252

Platform:
- macOS 13.5
- python 3.11.5

**To Reproduce**
`pip install temporai`
or 
` pip install "temporai @ git+https://github.com/vanderschaarlab/temporai@daa4af2e3943e5639098a4459464012c007245a3"`

**Expected behavior**
Build should not fail, and catboost should probably not be required. 

**Results**
temporai build fails.

```
Collecting catboost>=1.0.5 (from hyperimpute>=0.1.17->temporai@ git+https://github.com/vanderschaarlab/temporai@daa4af2e3943e5639098a4459464012c007245a3)
  Using cached catboost-1.2.2.tar.gz (60.1 MB)
```

<details>
```
  Building wheel for catboost (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for catboost (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [218 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-311
      creating build/lib.macosx-10.9-x86_64-cpython-311/catboost
      copying catboost/monoforest.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost
      copying catboost/plot_helpers.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost
      copying catboost/metrics.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost
      copying catboost/version.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost
      copying catboost/text_processing.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost
      copying catboost/datasets.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost
      copying catboost/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost
      copying catboost/core.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost
      copying catboost/utils.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost
      copying catboost/dev_utils.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost
      creating build/lib.macosx-10.9-x86_64-cpython-311/catboost/widget
      copying catboost/widget/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/widget
      copying catboost/widget/metrics_plotter.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/widget
      copying catboost/widget/ipythonwidget.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/widget
      copying catboost/widget/callbacks.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/widget
      creating build/lib.macosx-10.9-x86_64-cpython-311/catboost/eval
      copying catboost/eval/catboost_evaluation.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/eval
      copying catboost/eval/_fold_model.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/eval
      copying catboost/eval/_readers.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/eval
      copying catboost/eval/log_config.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/eval
      copying catboost/eval/_splitter.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/eval
      copying catboost/eval/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/eval
      copying catboost/eval/execution_case.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/eval
      copying catboost/eval/_fold_storage.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/eval
      copying catboost/eval/factor_utils.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/eval
      copying catboost/eval/utils.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/eval
      copying catboost/eval/evaluation_result.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/eval
      copying catboost/eval/_fold_models_handler.py -> build/lib.macosx-10.9-x86_64-cpython-311/catboost/eval
      running build_ext
      Buildling _catboost with cmake and ninja
      target_platform=darwin-x86_64. Building targets _catboost with PIC
      Running "cmake /private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-install-pvf83pvv/catboost_978ae68fc7434fc3857f456b847dec21/catboost_all_src -B /private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-install-pvf83pvv/catboost_978ae68fc7434fc3857f456b847dec21/build/temp.macosx-10.9-x86_64-cpython-311 -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-install-pvf83pvv/catboost_978ae68fc7434fc3857f456b847dec21/catboost_all_src/build/toolchains/clang.toolchain --log-level=VERBOSE -DCMAKE_POSITION_INDEPENDENT_CODE=On -DCATBOOST_COMPONENTS=python-package -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DHAVE_CUDA=no -DPython3_ROOT_DIR=/Users/jk1/opt/anaconda3/envs/treatment_effects"
      -- The C compiler identification is AppleClang 14.0.3.14030022
      -- The CXX compiler identification is AppleClang 14.0.3.14030022
      -- The ASM compiler identification is Clang
      -- Found assembler: /Library/Developer/CommandLineTools/usr/bin/clang
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/clang - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/clang++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Python3: /Users/jk1/opt/anaconda3/envs/treatment_effects/bin/python3.1 (found version "3.11.5") found components: Interpreter
      -- CMAKE_C_FLAGS = "   -fexceptions   -fno-common   -fcolor-diagnostics   -faligned-allocation   -fdebug-default-version=4   -ffunction-sections   -fdata-sections   -Wall   -Wextra   -Wno-parentheses   -Wno-implicit-const-int-float-conversion   -Wno-unknown-warning-option   -pipe   -D_THREAD_SAFE   -D_PTHREADS   -D_REENTRANT   -D_LARGEFILE_SOURCE   -D__STDC_CONSTANT_MACROS   -D__STDC_FORMAT_MACROS   -D__LONG_LONG_SUPPORTED  -DLIBCXX_BUILDING_LIBCXXRT -D_FILE_OFFSET_BITS=64 -m64    -msse2     -msse3     -mssse3         -msse4.1       -msse4.2       -mpopcnt      -mcx16     -DSSE_ENABLED=1     -DSSE3_ENABLED=1     -DSSSE3_ENABLED=1         -DSSE41_ENABLED=1       -DSSE42_ENABLED=1       -DPOPCNT_ENABLED=1      -DCX16_ENABLED=1"
      -- CMAKE_CXX_FLAGS = "   -fexceptions   -fno-common   -fcolor-diagnostics   -faligned-allocation   -fdebug-default-version=4   -ffunction-sections   -fdata-sections   -Wall   -Wextra   -Wno-parentheses   -Wno-implicit-const-int-float-conversion   -Wno-unknown-warning-option   -pipe   -D_THREAD_SAFE   -D_PTHREADS   -D_REENTRANT   -D_LARGEFILE_SOURCE   -D__STDC_CONSTANT_MACROS   -D__STDC_FORMAT_MACROS   -D__LONG_LONG_SUPPORTED  -DLIBCXX_BUILDING_LIBCXXRT -D_FILE_OFFSET_BITS=64 -m64    -msse2     -msse3     -mssse3         -msse4.1       -msse4.2       -mpopcnt      -mcx16   -Woverloaded-virtual   -Wimport-preprocessor-directive-pedantic   -Wno-undefined-var-template   -Wno-return-std-move   -Wno-defaulted-function-deleted   -Wno-pessimizing-move   -Wno-deprecated-anon-enum-enum-conversion   -Wno-deprecated-enum-enum-conversion   -Wno-deprecated-enum-float-conversion   -Wno-ambiguous-reversed-operator   -Wno-deprecated-volatile      -DSSE_ENABLED=1     -DSSE3_ENABLED=1     -DSSSE3_ENABLED=1         -DSSE41_ENABLED=1       -DSSE42_ENABLED=1       -DPOPCNT_ENABLED=1      -DCX16_ENABLED=1"
      -- Conan: checking conan executable
      -- Conan: Found program /private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/bin/conan
      -- Conan: Version found Conan version 1.59.0
      -- Conan executing: /private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/bin/conan install /private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-install-pvf83pvv/catboost_978ae68fc7434fc3857f456b847dec21/catboost_all_src --remote conancenter --install-folder /private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-install-pvf83pvv/catboost_978ae68fc7434fc3857f456b847dec21/build/temp.macosx-10.9-x86_64-cpython-311 --build missing --env CONAN_CMAKE_GENERATOR=Ninja --settings build_type=Release --settings compiler=apple-clang --settings compiler.version=14.0 --settings compiler.libcxx=libc++ --settings compiler.cppstd=20 --conf tools.cmake.cmaketoolchain:generator=Ninja
      Configuration:
      [settings]
      arch=x86_64
      arch_build=x86_64
      build_type=Release
      compiler=apple-clang
      compiler.cppstd=20
      compiler.libcxx=libc++
      compiler.version=14.0
      os=Macos
      os_build=Macos
      [options]
      [build_requires]
      [env]
      CONAN_CMAKE_GENERATOR=Ninja
      [conf]
      tools.cmake.cmaketoolchain:generator=Ninja
      
      Version ranges solved
          Version range '>=1.2.11 <2' required by 'pcre/8.45' resolved to 'zlib/1.3' in local cache
      
      conanfile.txt: Installing package
      Requirements
          libiconv/1.15 from 'conancenter' - Cache
          openssl/1.1.1t from 'conancenter' - Cache
      Packages
          libiconv/1.15:e1ef30a7ac2ff8c218173fdf49ec961a5c046a36 - Cache
          openssl/1.1.1t:a319f556f93546f2dff1b70922784b70e7cba919 - Cache
      Build requirements
          bzip2/1.0.8 from 'conancenter' - Cache
          pcre/8.45 from 'conancenter' - Cache
          ragel/6.10 from 'conancenter' - Cache
          swig/4.0.2 from 'conancenter' - Cache
          yasm/1.3.0 from 'conancenter' - Cache
          zlib/1.3 from 'conancenter' - Cache
      Build requirements packages
          bzip2/1.0.8:b9b85a7c8f543b96385e1da9e174853f1fb08e0c - Cache
          pcre/8.45:842afe377248eac66b64b538531df2b005d57959 - Cache
          ragel/6.10:801752c0480319b8e090188c566245a78e9abcf4 - Cache
          swig/4.0.2:099d7b9cd06e9bd11e92b9a2ddf3b29cd986fdcb - Cache
          yasm/1.3.0:801752c0480319b8e090188c566245a78e9abcf4 - Cache
          zlib/1.3:a319f556f93546f2dff1b70922784b70e7cba919 - Cache
      
      Installing (downloading, building) binaries...
      bzip2/1.0.8: Already installed!
      libiconv/1.15: Already installed!
      openssl/1.1.1t: Already installed!
      ragel/6.10: Already installed!
      ragel/6.10: Appending PATH environment variable: /Users/jk1/.conan/data/ragel/6.10/_/_/package/801752c0480319b8e090188c566245a78e9abcf4/bin
      yasm/1.3.0: Already installed!
      yasm/1.3.0: Appending PATH environment variable: /Users/jk1/.conan/data/yasm/1.3.0/_/_/package/801752c0480319b8e090188c566245a78e9abcf4/bin
      zlib/1.3: Already installed!
      pcre/8.45: Already installed!
      swig/4.0.2: Already installed!
      swig/4.0.2: Appending PATH environment variable: /Users/jk1/.conan/data/swig/4.0.2/_/_/package/099d7b9cd06e9bd11e92b9a2ddf3b29cd986fdcb/bin
      conanfile.txt: Applying build-requirement: ragel/6.10
      conanfile.txt: Applying build-requirement: swig/4.0.2
      conanfile.txt: Applying build-requirement: yasm/1.3.0
      conanfile.txt: Applying build-requirement: pcre/8.45
      conanfile.txt: Applying build-requirement: bzip2/1.0.8
      conanfile.txt: Applying build-requirement: zlib/1.3
      conanfile.txt: Generator cmake_find_package created Findragel.cmake
      conanfile.txt: Generator cmake_find_package created FindSWIG.cmake
      conanfile.txt: Generator cmake_find_package created Findyasm.cmake
      conanfile.txt: Generator cmake_find_package created FindIconv.cmake
      conanfile.txt: Generator cmake_find_package created FindOpenSSL.cmake
      conanfile.txt: Generator cmake_find_package created FindPCRE.cmake
      conanfile.txt: Generator cmake_find_package created FindBZip2.cmake
      conanfile.txt: Generator cmake_find_package created FindZLIB.cmake
      conanfile.txt: Generator cmake_paths created conan_paths.cmake
      conanfile.txt: Generator txt created conanbuildinfo.txt
      conanfile.txt: Aggregating env generators
      conanfile.txt: Generated conaninfo.txt
      conanfile.txt: Generated graphinfo
      conanfile.txt imports(): Copied 434 '.i' files
      conanfile.txt imports(): Copied 273 '.swg' files
      conanfile.txt imports(): Copied 1 '.swig' file: Makefile.swig
      conanfile.txt imports(): Copied 2 '.ml' files: swig.ml, swigp4.ml
      conanfile.txt imports(): Copied 1 '.pl' file: Makefile.pl
      conanfile.txt imports(): Copied 6 files
      conanfile.txt imports(): Copied 1 '.rb' file: extconf.rb
      conanfile.txt imports(): Copied 1 '.h' file: noembed.h
      conanfile.txt imports(): Copied 1 '.scm' file: common.scm
      conanfile.txt imports(): Copied 1 '.mli' file: swig.mli
      conanfile.txt imports(): Copied 1 '.hpp' file: octheaders.hpp
      CMake Error at /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Python3_LIBRARIES
        Development Development.Module Development.Embed)
      Call Stack (most recent call first):
        /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
        /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/FindPython/Support.cmake:3166 (find_package_handle_standard_args)
        /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/FindPython3.cmake:485 (include)
        catboost/python-package/catboost/CMakeLists.darwin-x86_64.txt:9 (find_package)
        catboost/python-package/catboost/CMakeLists.txt:20 (include)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-install-pvf83pvv/catboost_978ae68fc7434fc3857f456b847dec21/build/temp.macosx-10.9-x86_64-cpython-311/CMakeFiles/CMakeOutput.log".
      See also "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-install-pvf83pvv/catboost_978ae68fc7434fc3857f456b847dec21/build/temp.macosx-10.9-x86_64-cpython-311/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "/Users/jk1/opt/anaconda3/envs/treatment_effects/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/jk1/opt/anaconda3/envs/treatment_effects/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jk1/opt/anaconda3/envs/treatment_effects/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 731, in <module>
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 397, in run
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 332, in run
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-build-env-itfn3d2q/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 444, in run
        File "<string>", line 462, in build_with_cmake_and_ninja
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-install-pvf83pvv/catboost_978ae68fc7434fc3857f456b847dec21/catboost_all_src/build/build_native.py", line 517, in build
          cmd_runner.run(cmake_cmd, env=build_environ)
        File "/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-install-pvf83pvv/catboost_978ae68fc7434fc3857f456b847dec21/catboost_all_src/build/build_native.py", line 164, in run
          subprocess.run(cmd, check=True, **subprocess_run_kwargs)
        File "/Users/jk1/opt/anaconda3/envs/treatment_effects/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-install-pvf83pvv/catboost_978ae68fc7434fc3857f456b847dec21/catboost_all_src', '-B', '/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-install-pvf83pvv/catboost_978ae68fc7434fc3857f456b847dec21/build/temp.macosx-10.9-x86_64-cpython-311', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=/private/var/folders/9v/1s329cwj32jc2kkx24p8jp980000gp/T/pip-install-pvf83pvv/catboost_978ae68fc7434fc3857f456b847dec21/catboost_all_src/build/toolchains/clang.toolchain', '--log-level=VERBOSE', '-DCMAKE_POSITION_INDEPENDENT_CODE=On', '-DCATBOOST_COMPONENTS=python-package', '-DCMAKE_OSX_DEPLOYMENT_TARGET=11.0', '-DHAVE_CUDA=no', '-DPython3_ROOT_DIR=/Users/jk1/opt/anaconda3/envs/treatment_effects']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for catboost
Successfully built temporai
Failed to build catboost
ERROR: Could not build wheels for catboost, which is required to install pyproject.toml-based projects
```
</details>

**Comment by DrShushen** [comment]
Thank you for reporting this! We will investigate.

This may also be related to the fact that you are using Python 3.11 (which would affect dependencies), which we do not yet fully support. Could you try with Python 3.10 to see if that resolves the issue?

**Comment by JulianKlug** [comment]
The build works with python 3.10.
